### ISSUE TITLE
准备入坑的小白求指教

### ISSUE THREAD

**Issue by tlerbao** [myqqiu/Hackintosh-B460M-MORTAR-i5-10500-iGPU-UHD630#15]
> 实在等不及iMac跟新配置了，双十一准备先入坑黑果，自己写了下面配置以及问题求教。

### 拟定配置

CPU：I5 10400								
主板：MSI B460M Mortar												1939元/套
显卡：蓝宝石RX 590 GME 8G D5									1599元
内存：金士顿(Kingston) DDR4 2666 16GB(8G×2)		499元
硬盘：WD Blue SN550 1TB												789元
电源：酷冷至尊 650W GX650											469元
机箱：预算500左右待定													500元
蓝牙：BCM94360CD														256元
散热：利民 FS140																259元

Q1：MSI B460M Mortar	这主板直接可以插显卡和无线网卡吧，不用转接吧？
Q2：有没有必要必须上ATX主板和机箱？
Q3：10400有没有搭配的比较完美黑果的EFI的ATX主板型号推荐？
Q4：机箱有高颜值推荐吗？无需侧透和各种RGB
Q5：我以后可能使用有线网络，那么装的BCM94360网卡就是为蓝牙而生的是吧？可以混用是吧？
Q6：显卡是RX590还是5500XT？
Q7：以上所有配置请尽情吐槽，我不是土豪，能帮我省钱就太感谢了

**Comment by yangyangrsw** [comment]
处理器可以上 10500，更加接近白苹果，主板用迫击炮太浪费，微星b460m 爆破弹就够了，显卡蓝宝石5500xt吧，电源500w足够了，散热雅浚g3就行，机箱推荐先马刚出的智趣，但是最后买小尺寸电源。efi可以找bili up主付费定制:小明和他的女朋友

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Talent.Miao <notifications@github.com>
发送时间: Friday, October 16, 2020 9:37:57 PM
收件人: myqqiu/Hackintosh-B460M-MORTAR-i5-10500-iGPU-UHD630 <Hackintosh-B460M-MORTAR-i5-10500-iGPU-UHD630@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [myqqiu/Hackintosh-B460M-MORTAR-i5-10500-iGPU-UHD630] 准备入坑的小白求指教 (#15)


实在等不及iMac跟新配置了，双十一准备先入坑黑果，自己写了下面配置以及问题求教。

拟定配置

CPU：I5 10400
主板：MSI B460M Mortar 1939元/套
显卡：蓝宝石RX 590 GME 8G D5 1599元
内存：金士顿(Kingston) DDR4 2666 16GB(8G×2) 499元
硬盘：WD Blue SN550 1TB 789元
电源：酷冷至尊 650W GX650 469元
机箱：预算500左右待定 500元
蓝牙：BCM94360CD 256元
散热：利民 FS140 259元

Q1：MSI B460M Mortar 这主板直接可以插显卡和无线网卡吧，不用转接吧？
Q2：有没有必要必须上ATX主板和机箱？
Q3：10400有没有搭配的比较完美黑果的EFI的ATX主板型号推荐？
Q4：机箱有高颜值推荐吗？无需侧透和各种RGB
Q5：我以后可能使用有线网络，那么装的BCM94360网卡就是为蓝牙而生的是吧？可以混用是吧？
Q6：显卡是RX590还是5500XT？
Q7：以上所有配置请尽情吐槽，我不是土豪，能帮我省钱就太感谢了

―

**Comment by tlerbao** [comment]
@yangyangrsw 94360蓝牙无线网卡是否是必须？我板载网卡有线上网，加蓝牙适配器，能不能实现 隔空投送 随航 接力等功能？
