### ISSUE TITLE
升级bios，黑苹果卡logo

### ISSUE THREAD

**Issue by Mlxa0324** [myqqiu/Hackintosh-B460M-MORTAR-i5-10500-iGPU-UHD630#20]
如标题

**Comment by Zisbusy** [comment]
BIOS 版本7C82v13 发布日期2020-10-13 使用正常，检查下bios设置？

**Comment by Mlxa0324** [comment]
> BIOS 版本7C82v13 发布日期2020-10-13 使用正常，检查下bios设置？

找到原因了，CFG Lock 没关闭

**Comment by Mlxa0324** [comment]
> BIOS 版本7C82v13 发布日期2020-10-13 使用正常，检查下bios设置？

你升级11了吗

**Comment by Zisbusy** [comment]
> > BIOS 版本7C82v13 发布日期2020-10-13 使用正常，检查下bios设置？
> 
> 你升级11了吗

升了。
