### ISSUE TITLE
一个卑微phper黑果小白的一些疑问，请大佬解答。

### ISSUE THREAD

**Issue by tlerbao** [myqqiu/Hackintosh-B460M-MORTAR-i5-10500-iGPU-UHD630#23]
双十一入手了一批硬件，开始玩黑苹果，倒是已经用大佬的efi成功安装了，但是还有一些疑问。

我的配置：i5 10500 + B460M迫击炮 + LGUL850

1. 安装之前是否最好更新到和你仓库相同版本的BIOS。
2. BIOS设置只设置你reame里提到的几项就行吗，我看别的efi仓库都设置一堆BIOS。
3. 三码我用hackintool生成几个查询都非法，我看你自带这个可以，我可以用自带这个吗？
4. 我准备加装94360CD蓝牙无线网卡，咱们的efi支持吗还需要什么特殊设置吗，毕竟还是想使用隔空投送，接力什么的。

暂时这些，望大佬解答。

**Comment by fowlmouse** [comment]
路人甲围观建议https://github.com/corpnewt/GenSMBIOS
1. 安裝之前是否最好更新到和您倉庫相同版本的BIOS。
[路人甲]: 不需要
2. BIOS設置只設置你reame裡提到的幾項就行嗎，我看別的efi倉庫都設置一堆BIOS。
[路人甲]: 先安装 碰到问题再来问
3.三碼我用hackintool生成幾個查詢都非法，我看你自帶這個可以，我可以用自帶這個嗎？
[路人甲]: 一机一码 不建议参考 请参阅 https://github.com/corpnewt/GenSMBIOS 能绑ID 就不用担心
4.我準備加裝94360CD藍牙無線網卡，咱們的efi支持嗎還需要什麼特殊設置嗎，畢竟還是想使用隔空投送，接力什麼的
[路人甲]: 先安装 碰到问题再来问

**Comment by Luupw3d** [comment]
> 双十一入手了一批硬件，开始玩黑苹果，倒是已经用大佬的efi成功安装了，但是还有一些疑问。
> 
> 我的配置：i5 10500 + B460M迫击炮 + LGUL850
> 
> 1. 安装之前是否最好更新到和你仓库相同版本的BIOS。
> 2. BIOS设置只设置你reame里提到的几项就行吗，我看别的efi仓库都设置一堆BIOS。
> 3. 三码我用hackintool生成几个查询都非法，我看你自带这个可以，我可以用自带这个吗？
> 4. 我准备加装94360CD蓝牙无线网卡，咱们的efi支持吗还需要什么特殊设置吗，毕竟还是想使用隔空投送，接力什么的。
> 
> 暂时这些，望大佬解答。

同使用94360CD，不需要任何设置，插上即用，隔空投送亲测正常。

**Comment by tlerbao** [comment]
@fowlmouse 
暂时发现的问题就是本仓库的efi 两个前置usb2.0无法使用，不知有没有办法让他们可以使用
还有一个就是遇到了偶尔开机后整个系统没声音，重启后恢复正常的情况，不知为何。


@Luupw3d 
你的网卡蓝牙供电线插在了主板的哪个usb接口呢？

**Comment by Zisbusy** [comment]
同样双十一入手的硬件，
1.BIOS版本我用的最新的，没问题。
2.BIOS设置里的几项都是我总结测试过的，才写出来。
3.三码建议自己生成，不要跟其他人重复。
4.直接加装网卡即可，网卡的usb连接到距离io口侧最近的插座。各种功能正常使用。

**Comment by fowlmouse** [comment]
> @fowlmouse
> 暂时发现的问题就是本仓库的efi 两个前置usb2.0无法使用，不知有没有办法让他们可以使用
> 还有一个就是遇到了偶尔开机后整个系统没声音，重启后恢复正常的情况，不知为何。
> 
> @Luupw3d
> 你的网卡蓝牙供电线插在了主板的哪个usb接口呢？

我印象中V1.9版就解决了 我主板两个USB接口 9pin 有个用苹果网卡蓝牙供电可以动 另一个就是前置USB2.0 没问题

**Comment by fowlmouse** [comment]
> > @fowlmouse
> > 暂时发现的问题就是本仓库的efi 两个前置usb2.0无法使用，不知有没有办法让他们可以使用
> > 还有一个就是遇到了偶尔开机后整个系统没声音，重启后恢复正常的情况，不知为何。
> > @Luupw3d
> > 你的网卡蓝牙供电线插在了主板的哪个usb接口呢？
> 
> 我印象中V1.9版就解决了 我主板两个USB接口 9pin 有个用苹果网卡蓝牙供电可以动 另一个就是前置USB2.0 没问题

不管自制外接USB TYPE-A或是9pin 都没问题

**Comment by tlerbao** [comment]
@Zisbusy 
@fowlmouse 

你好，我现在也基本没问题了，买了网卡就等到货了，目前唯一问题就是 三个前置usb中的两个2.0不好使 插上没反应，另一个前置3.0好使，不知为何。我用hackintool 测试，插前置连个2.0任何一个都没有任何一个接口绿。

后置的usb全好用，typec还没测试。

**Comment by ocq4131** [comment]
> @Zisbusy
> @fowlmouse
> 
> 你好，我现在也基本没问题了，买了网卡就等到货了，目前唯一问题就是 三个前置usb中的两个2.0不好使 插上没反应，另一个前置3.0好使，不知为何。我用hackintool 测试，插前置连个2.0任何一个都没有任何一个接口绿。
> 
> 后置的usb全好用，typec还没测试。

我不确定你的问题,我用的Fractal Design D7C 机箱, U3 and U2 前方面板上的无问题.

**Comment by martincccc1992** [comment]
> 双十一入手了一批硬件，开始玩黑苹果，倒是已经用大佬的efi成功安装了，但是还有一些疑问。
> 
> 我的配置：i5 10500 + B460M迫击炮 + LGUL850
> 
> 1. 安装之前是否最好更新到和你仓库相同版本的BIOS。
> 2. BIOS设置只设置你reame里提到的几项就行吗，我看别的efi仓库都设置一堆BIOS。
> 3. 三码我用hackintool生成几个查询都非法，我看你自带这个可以，我可以用自带这个吗？
> 4. 我准备加装94360CD蓝牙无线网卡，咱们的efi支持吗还需要什么特殊设置吗，毕竟还是想使用隔空投送，接力什么的。
> 
> 暂时这些，望大佬解答。

同小白提问。。双十一购入这套价格多少？想比较下目前如坑性价比如何

**Comment by iihll** [comment]
微星主板只需先恢复默认设置，然后打开D.T.M选项即可，无需其他额外bios设置
