### ISSUE TITLE
同配置，4k 60hz dp输出，间歇黑屏、闪屏

### ISSUE THREAD

**Issue by Luupw3d** [myqqiu/Hackintosh-B460M-MORTAR-i5-10500-iGPU-UHD630#25]
更换Mac mini 18,1 机型序列号后有所好转，但仍不时出现。

**Comment by Zisbusy** [comment]
4k 表示正常，你win下有没有这种情况
![image](https://user-images.githubusercontent.com/49525016/99878795-d6e92780-2c42-11eb-8123-5322775206cb.png)

**Comment by Luupw3d** [comment]
Win10 v2004下测试无此问题
![image](https://user-images.githubusercontent.com/23554202/99881196-48c96d00-2c53-11eb-9acb-222a9f3ea3a8.png)

**Comment by dhb52** [comment]
尝试换个显示器试试，或者是线的问题。

**Comment by Luupw3d** [comment]
> 尝试换个显示器试试，或者是线的问题。

感谢，显示器原配线有此问题，已换Dell拆机线，问题解决。
