### ISSUE TITLE
Redundant configuration

### ISSUE THREAD

**Issue by IlikemacOS** [myqqiu/Hackintosh-B460M-MORTAR-i5-10500-iGPU-UHD630#3]
1.ACPI-Add-4-SSDT-RHUB.aml is not needed

2.I think you can use SSDT-UIAC.aml instead of USBPorts.kext and keep SSDT-EC-USBX.aml and USBInjectAll.kext

3.You can add a boot sound and streamline the files of Drivers

4.Your SSDT-PLUG.aml is too large

5.Misc-Tools Need Add ResetSystem.efi file,the name is shutdown or restart

**Comment by s20076001** [comment]
hey 
do you have any efi on this specs(b460m mortar, 10500 and igpu)?

**Comment by myqqiu** [comment]
Thank you, EFI optimized.
