### ISSUE TITLE
使用v2.1版的EFI，i5 10500 cpu 识别成了i9

### ISSUE THREAD

**Issue by QQ3233** [myqqiu/Hackintosh-B460M-MORTAR-i5-10500-iGPU-UHD630#39]
使用v2.1版的EFI，i5 10500 cpu 识别成了i9。iMac (Retina 5K, 27-inch, 2020)，3.1 GHz 六核Intel Core i9

**Comment by QQ3233** [comment]
iMac (Retina 5K, 27-inch, 2020)

**Comment by QQ3233** [comment]
3.1 GHz 六核Intel Core i9

**Comment by QQ3233** [comment]
iMac (Retina 5K, 27-inch, 2020)

**Comment by devhg** [comment]
我也出现同样的情况，而且瞬间变得特别卡，鼠标总是在转圈圈

**Comment by modanm** [comment]
OpenCore Configurator修改三码，这个位置改成0试试
![111](https://user-images.githubusercontent.com/76829855/104111656-8bd4c200-531f-11eb-9532-2332a98d5132.png)

**Comment by nagaame** [comment]
在机型这里修改, 我的这个是i7的
![1610264075327](https://user-images.githubusercontent.com/6214936/104117096-62d12300-5359-11eb-8561-84e8dc5372eb.jpg)

**Comment by QQ3233** [comment]
@nagaame @modanm 试了，还是不行

**Comment by nagaame** [comment]
> @nagaame @modanm 试了，还是不行

你已经在config.plist保存了这个平台的描述信息了嘛, ☑️右上角在config.plist里添加此部分内容, 然后各个CPU的一些类型描述信息


Clover 改马甲：

酷睿i3   0x0309

酷睿i5   0x0407、0x0601、0x0605 (优先使用)

酷睿i7   0x0701、0x0507、0x0705 (优先使用)

酷睿i9   0x1005.

志强系列 ：

0x0505 = Dual-Core Intel Xeon
0x0510 = Quad-Core Intel Xeon
0x05A5 = Quad-Core Intel Xeon
0x0506 = 6-Core Intel Xeon
0x0a01 = 8-Core Intel Xeon E5

OC改马甲：

对应的类型转换为10进制，例如我的I9 0x1005 转换为10进制 ，就填写 4101

比如我的是10700, 十代i7, 描述信息就是0x0705, 转换成十进制就是1797, 填进去, 然后保存, 重启试试看

**Comment by QQ3233** [comment]
> > @nagaame @modanm 试了，还是不行
> 
> 你已经在config.plist保存了这个平台的描述信息了嘛, ☑️右上角在config.plist里添加此部分内容, 然后各个CPU的一些类型描述信息
> 
> Clover 改马甲：
> 
> 酷睿i3 0x0309
> 
> 酷睿i5 0x0407、0x0601、0x0605 (优先使用)
> 
> 酷睿i7 0x0701、0x0507、0x0705 (优先使用)
> 
> 酷睿i9 0x1005.
> 
> 志强系列 ：
> 
> 0x0505 = Dual-Core Intel Xeon
> 0x0510 = Quad-Core Intel Xeon
> 0x05A5 = Quad-Core Intel Xeon
> 0x0506 = 6-Core Intel Xeon
> 0x0a01 = 8-Core Intel Xeon E5
> 
> OC改马甲：
> 
> 对应的类型转换为10进制，例如我的I9 0x1005 转换为10进制 ，就填写 4101
> 
> 比如我的是10700, 十代i7, 描述信息就是0x0705, 转换成十进制就是1797, 填进去, 然后保存, 重启试试看

可以了，原来是我16进制转化10进制算错了，非常感谢 @nagaame
