### ISSUE TITLE
睡眠/唤醒不能用。。

### ISSUE THREAD

**Issue by sanhaowuai** [myqqiu/Hackintosh-B460M-MORTAR-i5-10500-iGPU-UHD630#5]
您好 大佬 我用了您的EFI， 但是 睡眠/唤醒 这个功能不能用，我一睡眠就黑屏，用的是同样的配置b460m迫击炮+10500+核显，网上说是得关闭串行端口，但是我在这块主板上没找到这个设置，问卖主板的客服，她也不知道，不知道您是怎么解决的，望告知，谢谢！！

**Comment by anzi8** [comment]
使用EFI一次点亮进入。唤醒，键盘鼠标不行，需要按电源键。

**Comment by myqqiu** [comment]
键盘鼠标唤醒需BIOS设置才行，见文档。
