### ISSUE TITLE
Intel核显接口音频问题

### ISSUE THREAD

**Issue by dingdang66686** [myqqiu/Hackintosh-B460M-MORTAR-i5-10500-iGPU-UHD630#54]
核显HDMI口链接显示器没有声音，有解决方法吗？

**Comment by yangyangrsw** [comment]
视频接口没有定制，去我的仓库试试我那个efi

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Straying ***@***.***>
发送时间: Saturday, March 20, 2021 12:25:21 AM
收件人: myqqiu/Hackintosh-B460M-MORTAR-i5-10500-iGPU-UHD630 ***@***.***>
抄送: Subscribed ***@***.***>
主题: [myqqiu/Hackintosh-B460M-MORTAR-i5-10500-iGPU-UHD630] Intel核显接口音频问题 (#54)


核显HDMI口链接显示器没有声音，有解决方法吗？

―

**Comment by dingdang66686** [comment]
谢谢，这个问题我解决了，把device-property里声卡的no-hda参数去掉好像就可以了
