### ISSUE TITLE
黑果就这一个问题就完美了。

### ISSUE THREAD

**Issue by tlerbao** [myqqiu/Hackintosh-B460M-MORTAR-i5-10500-iGPU-UHD630#56]
10500+B460M迫击炮+5600XT

目前唯一一个问题，个别时候开机后进入输入密码界面之前黑屏，这个时候狂按回车啥的可以听到嘟嘟的声音，但是就是黑屏，极个别情况乱按后可能会进入输入密码界面，大部分时候需要重启才可以解决。

不知道有没有小哥遇到过，解决这个问题，黑果完美了！！！

**Comment by kuaner** [comment]
是显卡的问题 ，我遇到过，参考下面这个解决

https://github.com/baronerosso/asrock-x570-taichi-5700xt/issues/1#issuecomment-787081438

换显卡是最好的办法，你是撼讯的卡吗

**Comment by tlerbao** [comment]
> 是显卡的问题 ，我遇到过，参考下面这个解决
> 
> [baronerosso/asrock-x570-taichi-5700xt#1 (comment)](https://github.com/baronerosso/asrock-x570-taichi-5700xt/issues/1#issuecomment-787081438)
> 
> 换显卡是最好的办法，你是撼讯的卡吗


不是，我是蓝宝石的RX 5600XT

**Comment by tlerbao** [comment]
@kuaner 而且英文贼烂，能否帮忙说说怎么搞，是否适用我这个品牌的显卡。
