### ISSUE TITLE
关于UIScale的值，4K显示器到底设置多少

### ISSUE THREAD

**Issue by tlerbao** [myqqiu/Hackintosh-B460M-MORTAR-i5-10500-iGPU-UHD630#58]
按照本仓库作者的readme建议设置成Ag== 也就是01，设置成这样，在引导界面的UI图标什么的都比较小，尝试设置成02，就会比较大，感觉比较像1080P的样子，更舒服一点好像。

另一个差不多配置EFI仓库的作者是建议4K显示器设置成02的。

这个数值到底设置成多少是第一。

第二 这个数值是只影响引导界面的UI大小缩放，还是会影响其他地方。

**Comment by Zisbusy** [comment]
<key>UIScale</key>
<data>Ag==</data>
使用这个值，在我的4k显示器上，正常。

**Comment by tlerbao** [comment]
> UIScale
> Ag==
> 使用这个值，在我的4k显示器上，正常。

Ag== 就是01，会比较小，你试试改成02 呵呵新世界。

**Comment by tlerbao** [comment]
@Zisbusy 请问 SSDT-SHUT 是具体做什么的？

**Comment by taochangle** [comment]
4K 好像只有 30hz

**Comment by tlerbao** [comment]
> 4K 好像只有 30hz

我的60，要是30我得疯，LOL当年58 59 我就觉得卡了

**Comment by taochangle** [comment]
> > UIScale
> > Ag==
> > 使用这个值，在我的4k显示器上，正常。
> 
> Ag== 就是01，会比较小，你试试改成02 呵呵新世界。

4K 便携屏幕，01 02 开机后都一样，都能开启hidpi，02开机logo贼大

**Comment by tlerbao** [comment]
@taochangle 

官方文档给的是02是HiDPI，设置成02就好比把4K缩放成了1080P的形式（logo的大小，进度条等都是），进入系统默认也是UI类似1080P，不会有人用4K显示器真用4K原始分辨率的吧，眼睛不怕瞎的吗
![image](https://user-images.githubusercontent.com/20442232/114486509-9f563880-9c40-11eb-8a54-efa71ab21eea.png)
![image](https://user-images.githubusercontent.com/20442232/114486563-b85ee980-9c40-11eb-8caa-7b7820713887.png)

**Comment by taochangle** [comment]
> @taochangle
> 
> 官方文档给的是02是HiDPI，设置成02就好比把4K缩放成了1080P的形式（logo的大小，进度条等都是），进入系统默认也是UI类似1080P，不会有人用4K显示器真用4K原始分辨率的吧，眼睛不怕瞎的吗
> ![image](https://user-images.githubusercontent.com/20442232/114486509-9f563880-9c40-11eb-8a54-efa71ab21eea.png)
> ![image](https://user-images.githubusercontent.com/20442232/114486563-b85ee980-9c40-11eb-8caa-7b7820713887.png)

嗯嗯 是的，类1080P ，osx对于4K以上设备，应该是默认支持开启hidpi的，01，02 对于4k以上体验差别不大

**Comment by tlerbao** [comment]
@taochangle 01呢就是选择启动硬盘和读条的UI就都很小，但在输入密码之前还有一小段一闪而过的LOGO加进度条这个就是1080P的了，所以如果设置成一会有一个 从小到大的感觉，设置成02呢就全程包括到桌面后全是UI 1080P的样子，强迫症设置成2感觉好一点哈。

**Comment by taochangle** [comment]
> @taochangle 01呢就是选择启动硬盘和读条的UI就都很小，但在输入密码之前还有一小段一闪而过的LOGO加进度条这个就是1080P的了，所以如果设置成一会有一个 从小到大的感觉，设置成02呢就全程包括到桌面后全是UI 1080P的样子，强迫症设置成2感觉好一点哈。

👌   PHP同行啊 😂😂

**Comment by tlerbao** [comment]
@taochangle 菜鸡一枚，ThinkPHP6+Vue，老年Curd Boy

**Comment by yueqianW** [comment]
@tlerbao 你的 4k 显示器用的 dp 线连接吗，我用的双 hdmi 连接，会黑屏，没有显示信号

**Comment by hahadaxia007** [comment]
怎么修改  ag==02这样改吗
