### ISSUE TITLE
有人更新Big Sur 11.3.1了吗？听说要定制USB什么的？

### ISSUE THREAD

**Issue by tlerbao** [myqqiu/Hackintosh-B460M-MORTAR-i5-10500-iGPU-UHD630#62]
有人更新Big Sur 11.3.1了吗？听说要定制USB什么的？

用本仓库的EFI更新11.3.1会不会翻车。

**Comment by taochangle** [comment]
已更新，没发现问题

**Comment by QQ3233** [comment]
> 
> 
> 已更新，没发现问题

前置USB3.0接口插3.0U盘不识别，插2.0U盘能识别

**Comment by taochangle** [comment]
> > 已更新，没发现问题
> 
> 前置USB3.0接口插3.0U盘不识别，插2.0U盘能识别

![image](https://user-images.githubusercontent.com/7435144/118793444-314e0280-b8cb-11eb-9f7e-76e903e5a166.png)

**Comment by taochangle** [comment]
![image](https://user-images.githubusercontent.com/7435144/120060963-5beb4880-c08d-11eb-88bd-a0743f81a64d.png)
接着升了11.4 暂无不良反应,支持6800,6800xt 6900xt免驱,可惜连个580都没有😭

**Comment by QQ3233** [comment]
> ![image](https://user-images.githubusercontent.com/7435144/120060963-5beb4880-c08d-11eb-88bd-a0743f81a64d.png)
> 接着升了11.4 暂无不良反应,支持6800,6800xt 6900xt免驱,可惜连个580都没有😭

等矿难再入手

**Comment by yunzj770** [comment]
> ![image](https://user-images.githubusercontent.com/7435144/120060963-5beb4880-c08d-11eb-88bd-a0743f81a64d.png)
> 接着升了11.4 暂无不良反应,支持6800,6800xt 6900xt免驱,可惜连个580都没有😭

出了580,500块买了个460 869sp升级到了1024sp,用起来感觉和580没差
ae pr 跑的欢腾...
